preload = /home/Alberto/Imagens/Vazio.jpg

# O "eDP-1" costuma ser o nome padrão do ecrã integrado do portátil
wallpaper = eDP-1,/home/Alberto/Imagens/Vazio.jpg

# Desativa a mensagem de texto no fundo
splash = false

